# Generated by Django 4.2.23 on 2025-12-09 09:42

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('category_status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2025, 12, 9, 9, 42, 7, 605540, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_contact', models.CharField(max_length=15)),
                ('customer_address', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2025, 12, 9, 9, 42, 7, 606740, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_title', models.CharField(max_length=200)),
                ('menu_price', models.FloatField()),
                ('menu_description', models.TextField(blank=True, null=True)),
                ('menu_image', models.ImageField(blank=True, null=True, upload_to='menu_images/')),
                ('menu_status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2025, 12, 9, 9, 42, 7, 605540, tzinfo=datetime.timezone.utc))),
                ('menu_category', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='app_restaurant.category')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_code', models.CharField(max_length=100, unique=True)),
                ('order_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('order_status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], max_length=50)),
                ('discounted_price', models.FloatField(default=0.0)),
                ('coupen_code', models.CharField(blank=True, max_length=50, null=True)),
                ('vat_amount', models.FloatField(default=0.0)),
                ('total_price', models.FloatField()),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_status', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_restaurant.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.IntegerField(unique=True)),
                ('table_capacity', models.IntegerField()),
                ('table_status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2025, 12, 9, 9, 42, 7, 607248, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('item_price', models.FloatField()),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_restaurant.menu')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_restaurant.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_restaurant.table'),
        ),
    ]
