# Generated by Django 6.0.1 on 2026-01-18 07:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_restaurant', '0002_remove_order_customer_remove_order_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='stock_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 18, 7, 32, 3, 586343, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='menu',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 18, 7, 32, 3, 586343, tzinfo=datetime.timezone.utc)),
        ),
    ]
